version: "3.8"

networks:
  gateway:
    driver: bridge
  admin:
    driver: bridge


services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - gateway_db
      - admin
    env_file:
      - ./gateway/.env
    networks:
      - gateway

  admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    ports:
      - "8001:8000"
    networks:
      - admin
    env_file:
      - ./admin/.env
    volumes:
      - ./:/app
    depends_on:
      - admin_db


  gateway_db:
    image: mariadb
    restart: always
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      MYSQL_DATABASE: gateway
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - gateway
    volumes:
      - ./gateway/storage/database:/var/lib/mysql:rw
    user: root
    ports:
      - "3306:3306"

  admin_db:
    image: mariadb
    restart: always
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - admin
    volumes:
      - ./admin/storage/database:/var/lib/mysql:rw
    user: root
    ports:
      - "3307:3306"

volumes:
  admin_db:
  gateway_db: